version: "3.3"

services:

  nginx:
    image: alimizan/nginx-chat
    ports:
      - 80:80
    container_name: nginx
    build: nginx/
   
  pythonchat:
    image: alimizan/petclinic-backend:latest
    ports:
      - 5000:5000
    container_name: pythonchat
    build: .
