version: "3.3"

services:

#  nginx:
#    image: alimizan/nginx-chat
#    ports:
#      - 80:80
#    container_name: nginx
#    build: nginx/
   
  pythonchat:
    image: alimizan/python-chat-app:latest
    ports:
      - 5000:5000
    deploy:
      replicas: 1
    container_name: pythonchat
    build: .
